// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: coding_inference_queries.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const applyCodingInferenceGrantSettlement = `-- name: ApplyCodingInferenceGrantSettlement :exec
UPDATE coding_inference_grants
SET status = $1::text,
    bearer_digest = CASE WHEN $1::text = 'active' THEN bearer_digest ELSE NULL END,
    broker_public_key = CASE WHEN $1::text = 'active' THEN broker_public_key ELSE NULL END,
    prompt_tokens = prompt_tokens + $2::bigint,
    completion_tokens = completion_tokens + $3::bigint,
    cost_usd_micros = cost_usd_micros + $4::bigint,
    active_requests = 0,
    revoked_at = CASE
      WHEN $1::text = 'revoked' THEN COALESCE(revoked_at, $5::timestamptz)
      ELSE NULL
    END,
    updated_at = $5::timestamptz
WHERE grant_id = $6::uuid
`

type ApplyCodingInferenceGrantSettlementParams struct {
	Status           string             `json:"status"`
	PromptTokens     int64              `json:"promptTokens"`
	CompletionTokens int64              `json:"completionTokens"`
	CostUsdMicros    int64              `json:"costUsdMicros"`
	Now              pgtype.Timestamptz `json:"now"`
	GrantID          pgtype.UUID        `json:"grantId"`
}

func (q *Queries) ApplyCodingInferenceGrantSettlement(ctx context.Context, arg ApplyCodingInferenceGrantSettlementParams) error {
	_, err := q.db.Exec(ctx, applyCodingInferenceGrantSettlement,
		arg.Status,
		arg.PromptTokens,
		arg.CompletionTokens,
		arg.CostUsdMicros,
		arg.Now,
		arg.GrantID,
	)
	return err
}

const beginCodingInferenceGrantRequest = `-- name: BeginCodingInferenceGrantRequest :exec
UPDATE coding_inference_grants
SET request_count = request_count + $1::integer,
    active_requests = 1,
    updated_at = $2::timestamptz
WHERE grant_id = $3::uuid
`

type BeginCodingInferenceGrantRequestParams struct {
	RequestIncrement int32              `json:"requestIncrement"`
	Now              pgtype.Timestamptz `json:"now"`
	GrantID          pgtype.UUID        `json:"grantId"`
}

func (q *Queries) BeginCodingInferenceGrantRequest(ctx context.Context, arg BeginCodingInferenceGrantRequestParams) error {
	_, err := q.db.Exec(ctx, beginCodingInferenceGrantRequest, arg.RequestIncrement, arg.Now, arg.GrantID)
	return err
}

const countActiveCodingInferenceRequestsForValidator = `-- name: CountActiveCodingInferenceRequestsForValidator :one
SELECT COUNT(*)::bigint
FROM coding_inference_requests r
JOIN coding_inference_grants g ON g.grant_id = r.grant_id
WHERE r.status = 'started'
  AND g.status = 'active'
  AND g.expires_at > $1::timestamptz
  AND g.validator_hotkey = $2::text
`

type CountActiveCodingInferenceRequestsForValidatorParams struct {
	Now             pgtype.Timestamptz `json:"now"`
	ValidatorHotkey string             `json:"validatorHotkey"`
}

func (q *Queries) CountActiveCodingInferenceRequestsForValidator(ctx context.Context, arg CountActiveCodingInferenceRequestsForValidatorParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveCodingInferenceRequestsForValidator, arg.Now, arg.ValidatorHotkey)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countActiveCodingInferenceRequestsGlobal = `-- name: CountActiveCodingInferenceRequestsGlobal :one
SELECT COUNT(*)::bigint
FROM coding_inference_requests r
JOIN coding_inference_grants g ON g.grant_id = r.grant_id
WHERE r.status = 'started'
  AND g.status = 'active'
  AND g.expires_at > $1::timestamptz
`

func (q *Queries) CountActiveCodingInferenceRequestsGlobal(ctx context.Context, now pgtype.Timestamptz) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveCodingInferenceRequestsGlobal, now)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const findCodingInferenceSettlementIdentity = `-- name: FindCodingInferenceSettlementIdentity :one
SELECT request_row_id FROM coding_inference_requests
WHERE request_row_id <> $1::uuid
  AND (
    provider_settlement_sha256 = $2::text
    OR (
      $3::text IS NOT NULL
      AND provider_generation_id = $3::text
    )
  )
LIMIT 1
`

type FindCodingInferenceSettlementIdentityParams struct {
	RequestRowID             pgtype.UUID `json:"requestRowId"`
	ProviderSettlementSha256 string      `json:"providerSettlementSha256"`
	ProviderGenerationID     pgtype.Text `json:"providerGenerationId"`
}

func (q *Queries) FindCodingInferenceSettlementIdentity(ctx context.Context, arg FindCodingInferenceSettlementIdentityParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, findCodingInferenceSettlementIdentity, arg.RequestRowID, arg.ProviderSettlementSha256, arg.ProviderGenerationID)
	var request_row_id pgtype.UUID
	err := row.Scan(&request_row_id)
	return request_row_id, err
}

const getCodingDatabaseNow = `-- name: GetCodingDatabaseNow :one
SELECT clock_timestamp()::timestamptz
`

func (q *Queries) GetCodingDatabaseNow(ctx context.Context) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getCodingDatabaseNow)
	var column_1 pgtype.Timestamptz
	err := row.Scan(&column_1)
	return column_1, err
}

const getCodingInferenceGrant = `-- name: GetCodingInferenceGrant :one

SELECT grant_id, ticket_id, run_row_id, task_count, validator_hotkey, case_id, profile_capability_id, inference_grant_sha256, model, provider_api, provider_route, receipt_provider, provider_route_profile, provider_account_guardrail, provider_pipeline_policy, provider_cache_policy, reasoning_effort, status, bearer_digest, broker_public_key, generation, request_budget, prompt_token_budget, completion_token_budget, cost_budget_usd_micros, request_count, prompt_tokens, completion_tokens, cost_usd_micros, active_requests, expires_at, revoked_at, weight_eligible, created_at, updated_at FROM coding_inference_grants
WHERE grant_id = $1::uuid
`

// Shadow coding inference: the coding grant row is the per-grant
// serialization point. The handler always locks it before reading or writing
// request history, so two relay replicas cannot admit sibling dispatches.
func (q *Queries) GetCodingInferenceGrant(ctx context.Context, grantID pgtype.UUID) (CodingInferenceGrant, error) {
	row := q.db.QueryRow(ctx, getCodingInferenceGrant, grantID)
	var i CodingInferenceGrant
	err := row.Scan(
		&i.GrantID,
		&i.TicketID,
		&i.RunRowID,
		&i.TaskCount,
		&i.ValidatorHotkey,
		&i.CaseID,
		&i.ProfileCapabilityID,
		&i.InferenceGrantSha256,
		&i.Model,
		&i.ProviderApi,
		&i.ProviderRoute,
		&i.ReceiptProvider,
		&i.ProviderRouteProfile,
		&i.ProviderAccountGuardrail,
		&i.ProviderPipelinePolicy,
		&i.ProviderCachePolicy,
		&i.ReasoningEffort,
		&i.Status,
		&i.BearerDigest,
		&i.BrokerPublicKey,
		&i.Generation,
		&i.RequestBudget,
		&i.PromptTokenBudget,
		&i.CompletionTokenBudget,
		&i.CostBudgetUsdMicros,
		&i.RequestCount,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.CostUsdMicros,
		&i.ActiveRequests,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.WeightEligible,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCodingInferenceGrantForUpdate = `-- name: GetCodingInferenceGrantForUpdate :one
SELECT grant_id, ticket_id, run_row_id, task_count, validator_hotkey, case_id, profile_capability_id, inference_grant_sha256, model, provider_api, provider_route, receipt_provider, provider_route_profile, provider_account_guardrail, provider_pipeline_policy, provider_cache_policy, reasoning_effort, status, bearer_digest, broker_public_key, generation, request_budget, prompt_token_budget, completion_token_budget, cost_budget_usd_micros, request_count, prompt_tokens, completion_tokens, cost_usd_micros, active_requests, expires_at, revoked_at, weight_eligible, created_at, updated_at FROM coding_inference_grants
WHERE grant_id = $1::uuid
FOR UPDATE
`

func (q *Queries) GetCodingInferenceGrantForUpdate(ctx context.Context, grantID pgtype.UUID) (CodingInferenceGrant, error) {
	row := q.db.QueryRow(ctx, getCodingInferenceGrantForUpdate, grantID)
	var i CodingInferenceGrant
	err := row.Scan(
		&i.GrantID,
		&i.TicketID,
		&i.RunRowID,
		&i.TaskCount,
		&i.ValidatorHotkey,
		&i.CaseID,
		&i.ProfileCapabilityID,
		&i.InferenceGrantSha256,
		&i.Model,
		&i.ProviderApi,
		&i.ProviderRoute,
		&i.ReceiptProvider,
		&i.ProviderRouteProfile,
		&i.ProviderAccountGuardrail,
		&i.ProviderPipelinePolicy,
		&i.ProviderCachePolicy,
		&i.ReasoningEffort,
		&i.Status,
		&i.BearerDigest,
		&i.BrokerPublicKey,
		&i.Generation,
		&i.RequestBudget,
		&i.PromptTokenBudget,
		&i.CompletionTokenBudget,
		&i.CostBudgetUsdMicros,
		&i.RequestCount,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.CostUsdMicros,
		&i.ActiveRequests,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.WeightEligible,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCodingInferenceRequestForUpdate = `-- name: GetCodingInferenceRequestForUpdate :one
SELECT request_row_id, grant_id, ticket_id, generation, sequence, request_sequence, attempt, request_id, case_id, profile_capability_id, inference_grant_sha256, locked_request_sha256, status, provider_settlement_sha256, provider_generation_id, provider_settlement_json, unsettled_reason, started_at, settled_at, weight_eligible FROM coding_inference_requests
WHERE grant_id = $1::uuid
  AND sequence = $2::integer
FOR UPDATE
`

type GetCodingInferenceRequestForUpdateParams struct {
	GrantID  pgtype.UUID `json:"grantId"`
	Sequence int32       `json:"sequence"`
}

func (q *Queries) GetCodingInferenceRequestForUpdate(ctx context.Context, arg GetCodingInferenceRequestForUpdateParams) (CodingInferenceRequest, error) {
	row := q.db.QueryRow(ctx, getCodingInferenceRequestForUpdate, arg.GrantID, arg.Sequence)
	var i CodingInferenceRequest
	err := row.Scan(
		&i.RequestRowID,
		&i.GrantID,
		&i.TicketID,
		&i.Generation,
		&i.Sequence,
		&i.RequestSequence,
		&i.Attempt,
		&i.RequestID,
		&i.CaseID,
		&i.ProfileCapabilityID,
		&i.InferenceGrantSha256,
		&i.LockedRequestSha256,
		&i.Status,
		&i.ProviderSettlementSha256,
		&i.ProviderGenerationID,
		&i.ProviderSettlementJson,
		&i.UnsettledReason,
		&i.StartedAt,
		&i.SettledAt,
		&i.WeightEligible,
	)
	return i, err
}

const getLatestCodingInferenceRequestForUpdate = `-- name: GetLatestCodingInferenceRequestForUpdate :one
SELECT request_row_id, grant_id, ticket_id, generation, sequence, request_sequence, attempt, request_id, case_id, profile_capability_id, inference_grant_sha256, locked_request_sha256, status, provider_settlement_sha256, provider_generation_id, provider_settlement_json, unsettled_reason, started_at, settled_at, weight_eligible FROM coding_inference_requests
WHERE grant_id = $1::uuid
ORDER BY sequence DESC
LIMIT 1
FOR UPDATE
`

func (q *Queries) GetLatestCodingInferenceRequestForUpdate(ctx context.Context, grantID pgtype.UUID) (CodingInferenceRequest, error) {
	row := q.db.QueryRow(ctx, getLatestCodingInferenceRequestForUpdate, grantID)
	var i CodingInferenceRequest
	err := row.Scan(
		&i.RequestRowID,
		&i.GrantID,
		&i.TicketID,
		&i.Generation,
		&i.Sequence,
		&i.RequestSequence,
		&i.Attempt,
		&i.RequestID,
		&i.CaseID,
		&i.ProfileCapabilityID,
		&i.InferenceGrantSha256,
		&i.LockedRequestSha256,
		&i.Status,
		&i.ProviderSettlementSha256,
		&i.ProviderGenerationID,
		&i.ProviderSettlementJson,
		&i.UnsettledReason,
		&i.StartedAt,
		&i.SettledAt,
		&i.WeightEligible,
	)
	return i, err
}

const insertCodingInferenceRequest = `-- name: InsertCodingInferenceRequest :one
INSERT INTO coding_inference_requests (
    request_row_id,
    grant_id,
    ticket_id,
    generation,
    sequence,
    request_sequence,
    attempt,
    request_id,
    case_id,
    profile_capability_id,
    inference_grant_sha256,
    locked_request_sha256,
    status,
    provider_settlement_sha256,
    provider_generation_id,
    provider_settlement_json,
    unsettled_reason,
    started_at,
    settled_at,
    weight_eligible
) VALUES (
    $1::uuid,
    $2::uuid,
    $3::uuid,
    $4::integer,
    $5::integer,
    $6::integer,
    $7::integer,
    $8::uuid,
    $9::text,
    $10::text,
    $11::text,
    $12::text,
    'started',
    NULL,
    NULL,
    NULL,
    NULL,
    $13::timestamptz,
    NULL,
    false
)
RETURNING request_row_id, grant_id, ticket_id, generation, sequence, request_sequence, attempt, request_id, case_id, profile_capability_id, inference_grant_sha256, locked_request_sha256, status, provider_settlement_sha256, provider_generation_id, provider_settlement_json, unsettled_reason, started_at, settled_at, weight_eligible
`

type InsertCodingInferenceRequestParams struct {
	RequestRowID         pgtype.UUID        `json:"requestRowId"`
	GrantID              pgtype.UUID        `json:"grantId"`
	TicketID             pgtype.UUID        `json:"ticketId"`
	Generation           int32              `json:"generation"`
	Sequence             int32              `json:"sequence"`
	RequestSequence      int32              `json:"requestSequence"`
	Attempt              int32              `json:"attempt"`
	RequestID            pgtype.UUID        `json:"requestId"`
	CaseID               string             `json:"caseId"`
	ProfileCapabilityID  string             `json:"profileCapabilityId"`
	InferenceGrantSha256 string             `json:"inferenceGrantSha256"`
	LockedRequestSha256  string             `json:"lockedRequestSha256"`
	StartedAt            pgtype.Timestamptz `json:"startedAt"`
}

func (q *Queries) InsertCodingInferenceRequest(ctx context.Context, arg InsertCodingInferenceRequestParams) (CodingInferenceRequest, error) {
	row := q.db.QueryRow(ctx, insertCodingInferenceRequest,
		arg.RequestRowID,
		arg.GrantID,
		arg.TicketID,
		arg.Generation,
		arg.Sequence,
		arg.RequestSequence,
		arg.Attempt,
		arg.RequestID,
		arg.CaseID,
		arg.ProfileCapabilityID,
		arg.InferenceGrantSha256,
		arg.LockedRequestSha256,
		arg.StartedAt,
	)
	var i CodingInferenceRequest
	err := row.Scan(
		&i.RequestRowID,
		&i.GrantID,
		&i.TicketID,
		&i.Generation,
		&i.Sequence,
		&i.RequestSequence,
		&i.Attempt,
		&i.RequestID,
		&i.CaseID,
		&i.ProfileCapabilityID,
		&i.InferenceGrantSha256,
		&i.LockedRequestSha256,
		&i.Status,
		&i.ProviderSettlementSha256,
		&i.ProviderGenerationID,
		&i.ProviderSettlementJson,
		&i.UnsettledReason,
		&i.StartedAt,
		&i.SettledAt,
		&i.WeightEligible,
	)
	return i, err
}

const markCodingInferenceRequestUnsettled = `-- name: MarkCodingInferenceRequestUnsettled :exec
UPDATE coding_inference_requests
SET status = 'unsettled',
    provider_settlement_sha256 = NULL,
    provider_generation_id = NULL,
    provider_settlement_json = NULL,
    unsettled_reason = $1::text,
    settled_at = $2::timestamptz
WHERE request_row_id = $3::uuid
`

type MarkCodingInferenceRequestUnsettledParams struct {
	UnsettledReason string             `json:"unsettledReason"`
	SettledAt       pgtype.Timestamptz `json:"settledAt"`
	RequestRowID    pgtype.UUID        `json:"requestRowId"`
}

func (q *Queries) MarkCodingInferenceRequestUnsettled(ctx context.Context, arg MarkCodingInferenceRequestUnsettledParams) error {
	_, err := q.db.Exec(ctx, markCodingInferenceRequestUnsettled, arg.UnsettledReason, arg.SettledAt, arg.RequestRowID)
	return err
}

const revokeCodingInferenceGrantUnsettled = `-- name: RevokeCodingInferenceGrantUnsettled :exec
UPDATE coding_inference_grants
SET status = 'revoked',
    bearer_digest = NULL,
    broker_public_key = NULL,
    active_requests = 0,
    revoked_at = COALESCE(revoked_at, $1::timestamptz),
    updated_at = $1::timestamptz
WHERE grant_id = $2::uuid
`

type RevokeCodingInferenceGrantUnsettledParams struct {
	Now     pgtype.Timestamptz `json:"now"`
	GrantID pgtype.UUID        `json:"grantId"`
}

func (q *Queries) RevokeCodingInferenceGrantUnsettled(ctx context.Context, arg RevokeCodingInferenceGrantUnsettledParams) error {
	_, err := q.db.Exec(ctx, revokeCodingInferenceGrantUnsettled, arg.Now, arg.GrantID)
	return err
}

const settleCodingInferenceRequest = `-- name: SettleCodingInferenceRequest :exec
UPDATE coding_inference_requests
SET status = $1::text,
    provider_settlement_sha256 = $2::text,
    provider_generation_id = $3::text,
    provider_settlement_json = $4::text,
    unsettled_reason = NULL,
    settled_at = $5::timestamptz
WHERE request_row_id = $6::uuid
`

type SettleCodingInferenceRequestParams struct {
	Status                   string             `json:"status"`
	ProviderSettlementSha256 string             `json:"providerSettlementSha256"`
	ProviderGenerationID     pgtype.Text        `json:"providerGenerationId"`
	ProviderSettlementJson   string             `json:"providerSettlementJson"`
	SettledAt                pgtype.Timestamptz `json:"settledAt"`
	RequestRowID             pgtype.UUID        `json:"requestRowId"`
}

func (q *Queries) SettleCodingInferenceRequest(ctx context.Context, arg SettleCodingInferenceRequestParams) error {
	_, err := q.db.Exec(ctx, settleCodingInferenceRequest,
		arg.Status,
		arg.ProviderSettlementSha256,
		arg.ProviderGenerationID,
		arg.ProviderSettlementJson,
		arg.SettledAt,
		arg.RequestRowID,
	)
	return err
}
