// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type Ticketstatus string

const (
	TicketstatusIssued  Ticketstatus = "issued"
	TicketstatusScored  Ticketstatus = "scored"
	TicketstatusExpired Ticketstatus = "expired"
)

func (e *Ticketstatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Ticketstatus(s)
	case string:
		*e = Ticketstatus(s)
	default:
		return fmt.Errorf("unsupported scan type for Ticketstatus: %T", src)
	}
	return nil
}

type NullTicketstatus struct {
	Ticketstatus Ticketstatus `json:"ticketstatus"`
	Valid        bool         `json:"valid"` // Valid is true if Ticketstatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTicketstatus) Scan(value interface{}) error {
	if value == nil {
		ns.Ticketstatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Ticketstatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTicketstatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Ticketstatus), nil
}

type CodingInferenceGrant struct {
	GrantID                  pgtype.UUID        `json:"grantId"`
	TicketID                 pgtype.UUID        `json:"ticketId"`
	RunRowID                 pgtype.UUID        `json:"runRowId"`
	TaskCount                int32              `json:"taskCount"`
	ValidatorHotkey          string             `json:"validatorHotkey"`
	CaseID                   string             `json:"caseId"`
	ProfileCapabilityID      string             `json:"profileCapabilityId"`
	InferenceGrantSha256     string             `json:"inferenceGrantSha256"`
	Model                    string             `json:"model"`
	ProviderApi              string             `json:"providerApi"`
	ProviderRoute            string             `json:"providerRoute"`
	ReceiptProvider          string             `json:"receiptProvider"`
	ProviderRouteProfile     string             `json:"providerRouteProfile"`
	ProviderAccountGuardrail string             `json:"providerAccountGuardrail"`
	ProviderPipelinePolicy   string             `json:"providerPipelinePolicy"`
	ProviderCachePolicy      string             `json:"providerCachePolicy"`
	ReasoningEffort          string             `json:"reasoningEffort"`
	Status                   string             `json:"status"`
	BearerDigest             pgtype.Text        `json:"bearerDigest"`
	BrokerPublicKey          pgtype.Text        `json:"brokerPublicKey"`
	Generation               int32              `json:"generation"`
	RequestBudget            int32              `json:"requestBudget"`
	PromptTokenBudget        int64              `json:"promptTokenBudget"`
	CompletionTokenBudget    int64              `json:"completionTokenBudget"`
	CostBudgetUsdMicros      int64              `json:"costBudgetUsdMicros"`
	RequestCount             int32              `json:"requestCount"`
	PromptTokens             int64              `json:"promptTokens"`
	CompletionTokens         int64              `json:"completionTokens"`
	CostUsdMicros            int64              `json:"costUsdMicros"`
	ActiveRequests           int32              `json:"activeRequests"`
	ExpiresAt                pgtype.Timestamptz `json:"expiresAt"`
	RevokedAt                pgtype.Timestamptz `json:"revokedAt"`
	WeightEligible           bool               `json:"weightEligible"`
	CreatedAt                pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt                pgtype.Timestamptz `json:"updatedAt"`
}

type CodingInferenceRequest struct {
	RequestRowID             pgtype.UUID        `json:"requestRowId"`
	GrantID                  pgtype.UUID        `json:"grantId"`
	TicketID                 pgtype.UUID        `json:"ticketId"`
	Generation               int32              `json:"generation"`
	Sequence                 int32              `json:"sequence"`
	RequestSequence          int32              `json:"requestSequence"`
	Attempt                  int32              `json:"attempt"`
	RequestID                pgtype.UUID        `json:"requestId"`
	CaseID                   string             `json:"caseId"`
	ProfileCapabilityID      string             `json:"profileCapabilityId"`
	InferenceGrantSha256     string             `json:"inferenceGrantSha256"`
	LockedRequestSha256      string             `json:"lockedRequestSha256"`
	Status                   string             `json:"status"`
	ProviderSettlementSha256 pgtype.Text        `json:"providerSettlementSha256"`
	ProviderGenerationID     pgtype.Text        `json:"providerGenerationId"`
	ProviderSettlementJson   pgtype.Text        `json:"providerSettlementJson"`
	UnsettledReason          pgtype.Text        `json:"unsettledReason"`
	StartedAt                pgtype.Timestamptz `json:"startedAt"`
	SettledAt                pgtype.Timestamptz `json:"settledAt"`
	WeightEligible           bool               `json:"weightEligible"`
}

type ConfirmationBundleTicket struct {
	TicketID          pgtype.UUID        `json:"ticketId"`
	BundleID          pgtype.UUID        `json:"bundleId"`
	ValidatorHotkey   string             `json:"validatorHotkey"`
	SlotID            string             `json:"slotId"`
	Status            string             `json:"status"`
	Attempt           int32              `json:"attempt"`
	IssuedAt          pgtype.Timestamptz `json:"issuedAt"`
	Deadline          pgtype.Timestamptz `json:"deadline"`
	FailureReason     pgtype.Text        `json:"failureReason"`
	FailedAt          pgtype.Timestamptz `json:"failedAt"`
	CreatedAt         pgtype.Timestamptz `json:"createdAt"`
	FailureClass      pgtype.Text        `json:"failureClass"`
	FailureStage      pgtype.Text        `json:"failureStage"`
	PrepareRejection  pgtype.Text        `json:"prepareRejection"`
	PrepareRejectedAt pgtype.Timestamptz `json:"prepareRejectedAt"`
}

type ConfirmationInferenceGrant struct {
	GrantID            pgtype.UUID        `json:"grantId"`
	TicketID           pgtype.UUID        `json:"ticketId"`
	BundleID           pgtype.UUID        `json:"bundleId"`
	ValidatorHotkey    string             `json:"validatorHotkey"`
	Lane               string             `json:"lane"`
	Status             string             `json:"status"`
	BearerDigest       string             `json:"bearerDigest"`
	BrokerPublicKey    string             `json:"brokerPublicKey"`
	Generation         int32              `json:"generation"`
	Model              string             `json:"model"`
	Provider           string             `json:"provider"`
	RouteProvider      string             `json:"routeProvider"`
	ReceiptProvider    string             `json:"receiptProvider"`
	ProfileRevision    string             `json:"profileRevision"`
	RequestBudget      int32              `json:"requestBudget"`
	TokenBudget        int64              `json:"tokenBudget"`
	CostBudgetMicrousd int64              `json:"costBudgetMicrousd"`
	RequestCount       int32              `json:"requestCount"`
	PromptTokens       int64              `json:"promptTokens"`
	CompletionTokens   int64              `json:"completionTokens"`
	CostMicrousd       int64              `json:"costMicrousd"`
	ActiveRequests     int32              `json:"activeRequests"`
	ExpiresAt          pgtype.Timestamptz `json:"expiresAt"`
	CreatedAt          pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt          pgtype.Timestamptz `json:"updatedAt"`
}

type ConfirmationInferenceRequest struct {
	GrantID             pgtype.UUID        `json:"grantId"`
	Nonce               pgtype.UUID        `json:"nonce"`
	Generation          int32              `json:"generation"`
	Status              string             `json:"status"`
	Model               string             `json:"model"`
	ReservedTokens      int64              `json:"reservedTokens"`
	MaxChargeableTokens int64              `json:"maxChargeableTokens"`
	PromptTokens        int64              `json:"promptTokens"`
	CompletionTokens    int64              `json:"completionTokens"`
	CostMicrousd        int64              `json:"costMicrousd"`
	UpstreamProvider    pgtype.Text        `json:"upstreamProvider"`
	StartedAt           pgtype.Timestamptz `json:"startedAt"`
	CompletedAt         pgtype.Timestamptz `json:"completedAt"`
}

type InferenceConcurrencySettingsRevision struct {
	Revision       int32              `json:"revision"`
	ParentRevision int32              `json:"parentRevision"`
	Scope          string             `json:"scope"`
	Settings       []byte             `json:"settings"`
	Checksum       string             `json:"checksum"`
	Reason         string             `json:"reason"`
	Actor          string             `json:"actor"`
	CreatedAt      pgtype.Timestamptz `json:"createdAt"`
}

type InferenceGrant struct {
	GrantID                      pgtype.UUID        `json:"grantId"`
	AgentID                      pgtype.UUID        `json:"agentId"`
	BenchVersion                 int32              `json:"benchVersion"`
	ValidatorHotkey              string             `json:"validatorHotkey"`
	SlotID                       string             `json:"slotId"`
	TicketDeadline               pgtype.Timestamptz `json:"ticketDeadline"`
	Status                       string             `json:"status"`
	BearerDigest                 pgtype.Text        `json:"bearerDigest"`
	BrokerPublicKey              pgtype.Text        `json:"brokerPublicKey"`
	Generation                   int32              `json:"generation"`
	AllowedModels                []byte             `json:"allowedModels"`
	RequestBudget                int32              `json:"requestBudget"`
	TokenBudget                  int64              `json:"tokenBudget"`
	RequestCount                 int32              `json:"requestCount"`
	PromptTokens                 int64              `json:"promptTokens"`
	CompletionTokens             int64              `json:"completionTokens"`
	CostMicrousd                 int64              `json:"costMicrousd"`
	ActiveRequests               int32              `json:"activeRequests"`
	ExpiresAt                    pgtype.Timestamptz `json:"expiresAt"`
	CreatedAt                    pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt                    pgtype.Timestamptz `json:"updatedAt"`
	RouteProvider                pgtype.Text        `json:"routeProvider"`
	RouteProfile                 pgtype.Text        `json:"routeProfile"`
	RouteQuantization            pgtype.Text        `json:"routeQuantization"`
	RoutePromptPricePerToken     pgtype.Float8      `json:"routePromptPricePerToken"`
	RouteCompletionPricePerToken pgtype.Float8      `json:"routeCompletionPricePerToken"`
	EmbeddingModel               string             `json:"embeddingModel"`
	EmbeddingProfile             string             `json:"embeddingProfile"`
	EmbeddingProvider            string             `json:"embeddingProvider"`
	EmbeddingDimensions          int32              `json:"embeddingDimensions"`
	EmbeddingRequestBudget       int32              `json:"embeddingRequestBudget"`
	EmbeddingTokenBudget         int64              `json:"embeddingTokenBudget"`
	EmbeddingRequestCount        int32              `json:"embeddingRequestCount"`
	EmbeddingTokens              int64              `json:"embeddingTokens"`
	EmbeddingCostMicrousd        int64              `json:"embeddingCostMicrousd"`
	EmbeddingActiveRequests      int32              `json:"embeddingActiveRequests"`
	UsageAccountingVersion       int32              `json:"usageAccountingVersion"`
}

type InferenceProviderRoute struct {
	Model                     string             `json:"model"`
	Provider                  string             `json:"provider"`
	ProfileRevision           string             `json:"profileRevision"`
	Status                    string             `json:"status"`
	CalibrationStatus         string             `json:"calibrationStatus"`
	ContextLength             pgtype.Int4        `json:"contextLength"`
	Quantization              pgtype.Text        `json:"quantization"`
	PromptPricePerToken       pgtype.Float8      `json:"promptPricePerToken"`
	CompletionPricePerToken   pgtype.Float8      `json:"completionPricePerToken"`
	EwmaTokensPerSecond       pgtype.Float8      `json:"ewmaTokensPerSecond"`
	EwmaLatencyMs             pgtype.Float8      `json:"ewmaLatencyMs"`
	EwmaErrorRate             float64            `json:"ewmaErrorRate"`
	EwmaTimeoutRate           float64            `json:"ewmaTimeoutRate"`
	EwmaToolAccuracy          pgtype.Float8      `json:"ewmaToolAccuracy"`
	EwmaComposite             pgtype.Float8      `json:"ewmaComposite"`
	CalibrationToolAccuracy   pgtype.Float8      `json:"calibrationToolAccuracy"`
	CalibrationComposite      pgtype.Float8      `json:"calibrationComposite"`
	CalibrationSampleCount    int32              `json:"calibrationSampleCount"`
	CalibrationRevision       int32              `json:"calibrationRevision"`
	CalibrationManifestSha256 pgtype.Text        `json:"calibrationManifestSha256"`
	CalibratedAt              pgtype.Timestamptz `json:"calibratedAt"`
	EwmaCostMicrousd          pgtype.Float8      `json:"ewmaCostMicrousd"`
	SampleCount               int64              `json:"sampleCount"`
	SelectedTicketCount       int64              `json:"selectedTicketCount"`
	ExplorationTicketCount    int32              `json:"explorationTicketCount"`
	LastSelectedAt            pgtype.Timestamptz `json:"lastSelectedAt"`
	CooldownUntil             pgtype.Timestamptz `json:"cooldownUntil"`
	DiscoveredAt              pgtype.Timestamptz `json:"discoveredAt"`
	LastObservedAt            pgtype.Timestamptz `json:"lastObservedAt"`
	UpdatedAt                 pgtype.Timestamptz `json:"updatedAt"`
}

type InferenceRequest struct {
	GrantID             pgtype.UUID        `json:"grantId"`
	Nonce               pgtype.UUID        `json:"nonce"`
	Generation          int32              `json:"generation"`
	Status              string             `json:"status"`
	Model               string             `json:"model"`
	ReservedTokens      int64              `json:"reservedTokens"`
	PromptTokens        int64              `json:"promptTokens"`
	CompletionTokens    int64              `json:"completionTokens"`
	CostMicrousd        int64              `json:"costMicrousd"`
	StartedAt           pgtype.Timestamptz `json:"startedAt"`
	CompletedAt         pgtype.Timestamptz `json:"completedAt"`
	UpstreamProvider    pgtype.Text        `json:"upstreamProvider"`
	TimedOut            bool               `json:"timedOut"`
	LatencyMs           pgtype.Int4        `json:"latencyMs"`
	RequestKind         string             `json:"requestKind"`
	UpstreamAttempts    int32              `json:"upstreamAttempts"`
	MaxChargeableTokens int64              `json:"maxChargeableTokens"`
	OpenrouterAttempts  int32              `json:"openrouterAttempts"`
	FallbackPhase       int32              `json:"fallbackPhase"`
	TerminalErrorCode   pgtype.Text        `json:"terminalErrorCode"`
}

type InferenceRoutingPolicy struct {
	Model                   string             `json:"model"`
	Revision                int32              `json:"revision"`
	Enabled                 bool               `json:"enabled"`
	SpeedWeight             float64            `json:"speedWeight"`
	CostWeight              float64            `json:"costWeight"`
	ExplorationWeight       float64            `json:"explorationWeight"`
	ExplorationTicketBudget int32              `json:"explorationTicketBudget"`
	MinToolAccuracy         float64            `json:"minToolAccuracy"`
	MinComposite            float64            `json:"minComposite"`
	MinCalibrationSamples   int32              `json:"minCalibrationSamples"`
	MaxErrorRate            float64            `json:"maxErrorRate"`
	MaxTimeoutRate          float64            `json:"maxTimeoutRate"`
	CooldownSeconds         int32              `json:"cooldownSeconds"`
	EwmaAlpha               float64            `json:"ewmaAlpha"`
	UpdatedAt               pgtype.Timestamptz `json:"updatedAt"`
}

type ValidatorTicket struct {
	AgentID                 pgtype.UUID        `json:"agentId"`
	ValidatorHotkey         string             `json:"validatorHotkey"`
	Status                  Ticketstatus       `json:"status"`
	IssuedAt                pgtype.Timestamptz `json:"issuedAt"`
	Deadline                pgtype.Timestamptz `json:"deadline"`
	CreatedAt               pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt               pgtype.Timestamptz `json:"updatedAt"`
	BenchVersion            int32              `json:"benchVersion"`
	AttemptCount            int32              `json:"attemptCount"`
	RetryAfter              pgtype.Timestamptz `json:"retryAfter"`
	ManualRetryGrants       int32              `json:"manualRetryGrants"`
	InfraRetryGrants        int32              `json:"infraRetryGrants"`
	SlotID                  string             `json:"slotId"`
	Purpose                 string             `json:"purpose"`
	LegacyCompletionAllowed bool               `json:"legacyCompletionAllowed"`
	PurposeRevision         int32              `json:"purposeRevision"`
	Seed                    pgtype.Int8        `json:"seed"`
	DatasetSha256           pgtype.Text        `json:"datasetSha256"`
	SeedBlock               pgtype.Int8        `json:"seedBlock"`
	SeedBlockHash           pgtype.Text        `json:"seedBlockHash"`
	FailureReason           pgtype.Text        `json:"failureReason"`
	FailedAt                pgtype.Timestamptz `json:"failedAt"`
	FirstReportedAt         pgtype.Timestamptz `json:"firstReportedAt"`
	FailureDetail           pgtype.Text        `json:"failureDetail"`
	ContainerLogTail        pgtype.Text        `json:"containerLogTail"`
	ContainerLogTailAttempt pgtype.Int4        `json:"containerLogTailAttempt"`
}
